var express = require('express');
var cors = require('cors');

var expressApp = express();

var port = process.env.port || 3000;

console.log('Going to listen on %s', port);

var projects = [
    {id: 'portfolio', name: 'Portfolio', type: '1', description: 'You are currently navigating inside the Professional Portfolio website. It was built to demonstrate my proficiency using the latest trends in the technology industry.', tech: [{name:'Angular 6'}, {name:'Node.js'}, {name:'Express'}, {name:'Material'}, {name:'Flex Layout'}, {name:'Github'}, {name:'Azure'}]},
    {id: 'logsviewer', name: 'Logs Viewer', type: '1', description: 'Logs Viewer is an application we can use to display, filter and navigate easily trough the content of the log files generated by the log4net library.', tech: [{name:'MEAN stack'}, {name:'Log4Net'}, {name:'HTTP Services'}]},
    {id: 'admintool', name: 'Admin Tool', type: '1', description: 'Admin Tool is an application we can use to interact with a knowledge base, execute commands and perform custom actions.', tech: [{name:'MEAN stack'}, {name:'PowerShell'}]},
    {id: 'wordcup', name: 'Russia 2018', type: '2', description: 'Russia 2018 is a web application to follow the Russia 2018 Soccer World cup.', tech: [{name:'MEAN stack'}, {name:'Animation'}]},
    {id: 'homefinder', name: 'Home Finder', type: '2', description: 'Home Finder connects with newspaper feeds and parse the information about houses & departments.', tech: [{name:'C#'}, {name:'WPF & MVVM'}, {name:'SQL Server'}]}
   ];

var getProjects = function (req, res) {
    res.send(projects);
};

var getProfessionalProjects = function (req, res) {
    var professionalProjects = projects.filter(p => p.type == '1');
    res.send(professionalProjects);
};

var getFunProjects = function (req, res) {
    var funProjects = projects.filter(p => p.type == '2');
    res.send(funProjects);
};

expressApp.use(cors());

expressApp.get('/projects', getProjects);
expressApp.get('/funprojects', getFunProjects);
expressApp.get('/professionalprojects', getProfessionalProjects);

expressApp.listen(port);

console.log('Node.js server created.');